services:
  postgres:
    image: postgres:16.4-alpine
    container_name: stacheoverflow_postgres
    environment:
      POSTGRES_DB: stacheoverflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
